# Basic Information 
title: Meng Wu
position: Graduate Research Assistant
affiliation: Michigan Technological University
email: mewu@mtu.edu

# Search Engine Optimization (SEO)
description: Meng Wu is an Graduate Research Assistant at Michigan Technological University.

# The option is used to enable the Illinois template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=67O3Z3YAAAAJ
ORCID: https://orcid.org/0000-0003-2182-5856
linkedin: https://www.linkedin.com/in/meng-wu-a0658a26b/

# Images 
avatar: /assets/images/profile.jpg





# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
